
services:
  web:
    build: .
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: proiectdb
    volumes:
      - db-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
