apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30081  # Poți schimba cu orice între 30000-32767
      

