apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80          # portul pe care îl folosește aplicația în container
      targetPort: 80    # portul din container
      nodePort: 30082   # portul expus pe nod (alege între 30000-32767)
